# permissions for end users to view merries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: merry-viewer-role
rules:
- apiGroups:
  - infra.demo.com
  resources:
  - merries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - infra.demo.com
  resources:
  - merries/status
  verbs:
  - get
